// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Plataforma.Educacao.Faturamento.Data.Contexts;

#nullable disable

namespace Plataforma.Educacao.Faturamento.Data.Migrations
{
    [DbContext(typeof(FaturamentoDbContext))]
    partial class FaturamentoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.15");

            modelBuilder.Entity("Plataforma.Educacao.Faturamento.Domain.Entities.Pagamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UniqueIdentifier")
                        .HasColumnName("PagamentoId");

                    b.Property<string>("CodigoConfirmacaoPagamento")
                        .HasMaxLength(100)
                        .HasColumnType("Varchar")
                        .HasColumnName("CodigoConfirmacaoPagamento")
                        .UseCollation("Latin1_General_CI_AI");

                    b.Property<DateTime?>("DataPagamento")
                        .HasColumnType("SmallDateTime")
                        .HasColumnName("DataPagamento");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("SmallDateTime")
                        .HasColumnName("DataVencimento");

                    b.Property<Guid>("MatriculaId")
                        .HasColumnType("UniqueIdentifier")
                        .HasColumnName("MatriculaId");

                    b.Property<decimal>("Valor")
                        .HasPrecision(10, 2)
                        .HasColumnType("Money")
                        .HasColumnName("Valor");

                    b.HasKey("Id")
                        .HasName("PagamentosPK");

                    b.HasIndex("DataVencimento")
                        .HasDatabaseName("PagamentoDataVencimentoIDX");

                    b.ToTable("Pagamentos", (string)null);
                });

            modelBuilder.Entity("Plataforma.Educacao.Faturamento.Domain.Entities.Pagamento", b =>
                {
                    b.OwnsOne("Plataforma.Educacao.Faturamento.Domain.ValueObjects.DadosCartao", "Cartao", b1 =>
                        {
                            b1.Property<Guid>("PagamentoId")
                                .HasColumnType("UniqueIdentifier");

                            b1.Property<string>("CVV")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("Varchar")
                                .HasColumnName("CVVCartao")
                                .UseCollation("Latin1_General_CI_AI");

                            b1.Property<string>("NomeTitular")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("Varchar")
                                .HasColumnName("NomeTitularCartao")
                                .UseCollation("Latin1_General_CI_AI");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("Varchar")
                                .HasColumnName("NumeroCartao")
                                .UseCollation("Latin1_General_CI_AI");

                            b1.Property<string>("Validade")
                                .IsRequired()
                                .HasMaxLength(5)
                                .HasColumnType("Varchar")
                                .HasColumnName("ValidadeCartao")
                                .UseCollation("Latin1_General_CI_AI");

                            b1.HasKey("PagamentoId");

                            b1.ToTable("Pagamentos");

                            b1.WithOwner()
                                .HasForeignKey("PagamentoId");
                        });

                    b.OwnsOne("Plataforma.Educacao.Faturamento.Domain.ValueObjects.StatusPagamento", "StatusPagamento", b1 =>
                        {
                            b1.Property<Guid>("PagamentoId")
                                .HasColumnType("UniqueIdentifier");

                            b1.Property<int>("Status")
                                .HasColumnType("TinyInt")
                                .HasColumnName("Status");

                            b1.HasKey("PagamentoId");

                            b1.ToTable("Pagamentos");

                            b1.WithOwner()
                                .HasForeignKey("PagamentoId");
                        });

                    b.Navigation("Cartao");

                    b.Navigation("StatusPagamento");
                });
#pragma warning restore 612, 618
        }
    }
}
