// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Plataforma.Educacao.Conteudo.Data.Contexts;

#nullable disable

namespace Plataforma.Educacao.Conteudo.Data.Migrations
{
    [DbContext(typeof(ConteudoDbContext))]
    partial class ConteudoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.15");

            modelBuilder.Entity("Plataforma.Educacao.Conteudo.Domain.Entities.Aula", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UniqueIdentifier")
                        .HasColumnName("AulaId");

                    b.Property<bool>("Ativo")
                        .HasColumnType("Bit")
                        .HasColumnName("Ativo");

                    b.Property<short>("CargaHoraria")
                        .HasColumnType("SmallInt")
                        .HasColumnName("CargaHoraria");

                    b.Property<Guid>("CursoId")
                        .HasColumnType("UniqueIdentifier")
                        .HasColumnName("CursoId");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("Varchar")
                        .HasColumnName("Descricao")
                        .UseCollation("Latin1_General_CI_AI");

                    b.Property<byte>("OrdemAula")
                        .HasColumnType("TinyInt")
                        .HasColumnName("OrdemAula");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("Varchar")
                        .HasColumnName("Url")
                        .UseCollation("Latin1_General_CI_AI");

                    b.HasKey("Id")
                        .HasName("AulasPK");

                    b.HasIndex("CursoId");

                    b.HasIndex("Descricao")
                        .HasDatabaseName("AulasDescricaoIDX");

                    b.ToTable("Aulas", null, t =>
                        {
                            t.HasCheckConstraint("AulasCargaHorariaConstraint", "[CargaHoraria] Between 1 and 5");

                            t.HasCheckConstraint("AulasOrdemAulaConstraint", "[OrdemAula] > 0");
                        });
                });

            modelBuilder.Entity("Plataforma.Educacao.Conteudo.Domain.Entities.Curso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UniqueIdentifier")
                        .HasColumnName("CursoId");

                    b.Property<bool>("Ativo")
                        .HasColumnType("Bit")
                        .HasColumnName("Ativo");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("Varchar")
                        .HasColumnName("Nome")
                        .UseCollation("Latin1_General_CI_AI");

                    b.Property<DateTime?>("ValidoAte")
                        .HasColumnType("SmallDateTime")
                        .HasColumnName("ValidoAte");

                    b.Property<decimal>("Valor")
                        .HasPrecision(10, 2)
                        .HasColumnType("Money")
                        .HasColumnName("Valor");

                    b.HasKey("Id")
                        .HasName("CursosPK");

                    b.HasIndex("Nome")
                        .HasDatabaseName("CursosNomeIDX");

                    b.ToTable("Cursos", (string)null);
                });

            modelBuilder.Entity("Plataforma.Educacao.Conteudo.Domain.Entities.Aula", b =>
                {
                    b.HasOne("Plataforma.Educacao.Conteudo.Domain.Entities.Curso", "Curso")
                        .WithMany("Aulas")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("CursoAulaFK");

                    b.Navigation("Curso");
                });

            modelBuilder.Entity("Plataforma.Educacao.Conteudo.Domain.Entities.Curso", b =>
                {
                    b.OwnsOne("Plataforma.Educacao.Conteudo.Domain.ValueObjects.ConteudoProgramatico", "ConteudoProgramatico", b1 =>
                        {
                            b1.Property<Guid>("CursoId")
                                .HasColumnType("UniqueIdentifier");

                            b1.Property<string>("Ementa")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("Varchar")
                                .HasColumnName("Ementa")
                                .UseCollation("Latin1_General_CI_AI");

                            b1.Property<string>("Finalidade")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("Varchar")
                                .HasColumnName("Finalidade")
                                .UseCollation("Latin1_General_CI_AI");

                            b1.HasKey("CursoId");

                            b1.ToTable("Cursos");

                            b1.WithOwner()
                                .HasForeignKey("CursoId");
                        });

                    b.Navigation("ConteudoProgramatico");
                });

            modelBuilder.Entity("Plataforma.Educacao.Conteudo.Domain.Entities.Curso", b =>
                {
                    b.Navigation("Aulas");
                });
#pragma warning restore 612, 618
        }
    }
}
